---
project_name: edsrv
dist: bin/dist

builds:
  - id: edsrv
    binary: edsrv
    goos:
      - darwin
      - linux
    env:
      - GOFLAGS={{ .Env.GOFLAGS }}
      - CGO_ENABLED={{ .Env.CGO_ENABLED }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS }}
    main: cmd/edsrv/main.go
    goarch:
      - arm64
      - amd64
