---
project_name: edsrv
dist: bin/dist

builds:
  - id: edsrv
    binary: edsrv
    goos:
      - darwin
      - linux
    env:
      - GOFLAGS={{ .Env.GOFLAGS }}
      - CGO_LDFLAGS={{ .Env.CGO_LDFLAGS }}
    main: cmd/edsrv/main.go
    flags:
      - -a
    goarch:
      - arm64
      - amd64
