---
name: release

on:
  workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/go

      - name: Release
        run: make release
